# Generated by Django 5.2.11 on 2026-03-13 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('tenants', '0002_categoryroletemplate_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_customized',
            field=models.BooleanField(default=False, help_text="True if clinic has locally customized this role's permissions"),
        ),
        migrations.AddField(
            model_name='role',
            name='source_template',
            field=models.ForeignKey(blank=True, help_text='Template this role was provisioned from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_roles', to='tenants.categoryroletemplate'),
        ),
    ]
