# Generated by Django 5.2.11 on 2026-03-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Linked Stripe Price ID', max_length=100, null=True),
        ),
    ]
