# Generated by Django 5.2.11 on 2026-03-31 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagemetric',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='usagemetric',
            unique_together={('tenant', 'metric_type', 'month')},
        ),
    ]
