# Generated by Django 5.2.11 on 2026-02-24 09:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('trigger_event', models.CharField(choices=[('apt_booked', 'Appointment Booked'), ('apt_reminder', 'Appointment Reminder'), ('apt_followup', 'Appointment Follow-up'), ('payment_recv', 'Payment Received'), ('welcome', 'Welcome Message (New Patient)')], max_length=20)),
                ('offset_hours', models.IntegerField(default=0, help_text='Hours before (negative) or after (positive) the event')),
                ('is_active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='communications.messagetemplate')),
            ],
            options={
                'db_table': 'automation_rules',
            },
        ),
    ]
