# Generated by Django 5.2.11 on 2026-03-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('dial_code', models.CharField(help_text='e.g. +91', max_length=10)),
                ('iso_code', models.CharField(help_text='e.g. IN, US', max_length=5, unique=True)),
                ('flag_logo', models.ImageField(blank=True, null=True, upload_to='countries/flags/')),
                ('status', models.BooleanField(default=True, help_text='Is this country active for selection?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
    ]
