# Generated by Django 5.2.11 on 2026-03-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_currency_dateformat_language_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag_url',
            field=models.CharField(blank=True, help_text='URL for the country flag (e.g. from FlagCDN)', max_length=255, null=True),
        ),
    ]
