# Generated by Django 5.2.11 on 2026-02-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='category',
            field=models.CharField(choices=[('CLINIC', 'Clinic'), ('PHARMACY', 'Pharmacy'), ('HOSPITAL', 'Hospital'), ('LAB', 'Lab')], default='CLINIC', max_length=20),
        ),
    ]
