# Generated by Django 5.2.11 on 2026-03-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryroletemplate',
            name='code',
            field=models.CharField(blank=True, default='', help_text='Unique identifier for this role within the category (e.g. doctor, receptionist)', max_length=50),
        ),
        migrations.AddField(
            model_name='categoryroletemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this role currently active?'),
        ),
    ]
