# Generated by Django 5.2.11 on 2026-02-20 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_category'),
        ('tenants', '0002_tenantcategory_tenant_category'),
    ]

    operations = [
    ]
