# Generated by Django 5.2.11 on 2026-03-09 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0002_backfill_category_obj'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRoleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_admin_role', models.BooleanField(default=False, help_text='Should the onboarding user receive this role?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_templates', to='tenants.category')),
                ('permissions', models.ManyToManyField(blank=True, to='accounts.permission')),
            ],
            options={
                'ordering': ['category', '-is_admin_role', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
    ]
