# Generated by Django 5.2.11 on 2026-03-13 09:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_categoryroletemplate_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(help_text='Short title for the banner (e.g. SYSTEM MAINTENANCE)', max_length=255)),
                ('message', models.TextField(help_text='Detailed message text')),
                ('target_type', models.CharField(choices=[('ALL', 'All Tenants'), ('CATEGORY', 'Specific Categories'), ('SPECIFIC', 'Specific Tenants')], default='ALL', max_length=20)),
                ('target_categories', models.JSONField(blank=True, default=list, help_text='List of category codes if TARGET=CATEGORY')),
                ('is_active', models.BooleanField(default=False, help_text='If True, this banner currently displays. Only one can be active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_broadcasts', to=settings.AUTH_USER_MODEL)),
                ('target_tenants', models.ManyToManyField(blank=True, help_text='Specific tenants if TARGET=SPECIFIC', related_name='broadcasts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'broadcast_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
