# Generated by Django 5.2.11 on 2026-03-09 12:04

from django.db import migrations

def seed_category_templates(apps, schema_editor):
    Category = apps.get_model('tenants', 'Category')
    CategoryRoleTemplate = apps.get_model('tenants', 'CategoryRoleTemplate')
    Permission = apps.get_model('accounts', 'Permission')

    # Find the Clinic Category
    clinic_category = Category.objects.filter(code='CLINIC').first()
    if not clinic_category:
        return

    # Define templates exactly as they were in utils.py
    roles_config = {
        "Admin": {
            "desc": "Full access to the system",
            "perms": "ALL",
            "is_admin": True
        },
        "Clinic Manager": {
            "desc": "Manage operations, staff, and view reports",
            "perms": [
                "dashboard.clinic", "staff.view", "staff.manage", 
                "patient.view", "appointment.view", "billing.view",
            ],
            "is_admin": False
        },
        "Doctor": {
            "desc": "Manage patient records, prescriptions, and lab orders",
            "perms": [
                "dashboard.doctor", "patient.view", "patient.update", 
                "appointment.view", "prescription.view", "prescription.create",
                "lab.view", "lab.order"
            ],
            "is_admin": False
        },
        "Nurse": {
            "desc": "Patient vitals, assisting doctors, and appointments",
            "perms": [
                "dashboard.reception", "patient.view", "patient.update",
                "appointment.view", "appointment.create"
            ],
            "is_admin": False
        },
        "Receptionist": {
            "desc": "Patient registration, scheduling, and billing overview",
            "perms": [
                "dashboard.reception", "patient.view", "patient.create",
                "appointment.view", "appointment.create", "appointment.update", "appointment.cancel",
                "billing.view", "billing.create"
            ],
            "is_admin": False
        },
        "Lab Technician": {
            "desc": "Upload lab results and manage lab inventory",
            "perms": [
                "dashboard.lab", "lab.view", "lab.upload_results", "lab.manage_inventory"
            ],
            "is_admin": False
        },
        "Pharmacist": {
            "desc": "Manage prescriptions and inventory",
            "perms": [
                "dashboard.pharmacy", "pharmacy.view", "pharmacy.manage_inventory",
                "prescription.view", "prescription.dispense"
            ],
            "is_admin": False
        },
        "Patient": {
            "desc": "View personal records and book appointments",
            "perms": [
                "dashboard.patient", "patient.view", "appointment.view", "appointment.create",
                "lab.view", "prescription.view", "billing.view"
            ],
            "is_admin": False
        }
    }

    all_perms_obj = list(Permission.objects.all())
    all_perms_dict = {p.code: p for p in all_perms_obj}

    for role_name, config in roles_config.items():
        template, created = CategoryRoleTemplate.objects.get_or_create(
            category=clinic_category,
            name=role_name,
            defaults={
                "description": config["desc"],
                "is_admin_role": config["is_admin"]
            }
        )

        # Map permissions
        if config["perms"] == "ALL":
            template.permissions.set(all_perms_obj)
        else:
            selected_perms = []
            for code in config["perms"]:
                if code in all_perms_dict:
                    selected_perms.append(all_perms_dict[code])
            template.permissions.set(selected_perms)

def reverse_seed(apps, schema_editor):
    Category = apps.get_model('tenants', 'Category')
    CategoryRoleTemplate = apps.get_model('tenants', 'CategoryRoleTemplate')
    clinic_category = Category.objects.filter(code='CLINIC').first()
    if clinic_category:
        CategoryRoleTemplate.objects.filter(category=clinic_category).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_category_role_template'),
    ]

    operations = [
        migrations.RunPython(seed_category_templates, reverse_seed),
    ]
