# Generated by Django 5.2.11 on 2026-03-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_broadcastmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Linked Stripe Price ID', max_length=100, null=True),
        ),
    ]
