# Generated by Django 5.2.11 on 2026-02-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_merge_20260220_1539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantCategory',
        ),
    ]
