# Generated by Django 5.2.11 on 2026-03-23 05:09

from django.db import migrations


def migrate_data(apps, schema_editor):
    Tenant = apps.get_model('tenants', 'Tenant')
    ClinicSettings = apps.get_model('tenants', 'ClinicSettings')

    for settings in ClinicSettings.objects.all():
        tenant = settings.tenant
        tenant.logo = settings.logo
        tenant.address = settings.address
        tenant.gst_number = settings.gst_number
        tenant.registration_number = settings.registration_number
        tenant.timezone = settings.timezone
        tenant.currency = settings.currency
        tenant.language = settings.language
        tenant.date_format = settings.date_format
        tenant.working_hours = settings.working_hours
        tenant.holidays = settings.holidays
        tenant.emergency_available = settings.emergency_available
        tenant.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_address_tenant_currency_tenant_date_format_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_data, migrations.RunPython.noop),
    ]
