# Generated by Django 5.2.11 on 2026-03-23 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_migrate_clinic_settings_to_tenant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClinicSettings',
        ),
    ]
