# Generated by Django 5.2.11 on 2026-02-25 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_subscriptionplan_advanced_reports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_record', to='tenants.client'),
        ),
    ]
