# Generated by Django 5.2.11 on 2026-03-23 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_currency_dateformat_language_timezone_and_more'),
        ('tenants', '0006_remove_tenant_email_tenant_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='core.currency'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='date_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='core.dateformat'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='core.language'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='timezone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='core.timezone'),
        ),
    ]
