# Generated by Django 5.2.11 on 2026-03-06 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_subscriptionplan_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Uppercase code like CLINIC, PHARMACY', max_length=30, unique=True)),
                ('name', models.CharField(help_text="Display name, e.g. 'Clinics'", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Short description for the category card')),
                ('icon', models.CharField(choices=[('local_hospital', 'Hospital/Clinic'), ('medication', 'Medication/Pharmacy'), ('apartment', 'Building/Hospital'), ('biotech', 'Lab/Biotech'), ('healing', 'Healing'), ('psychology', 'Psychology'), ('elderly', 'Elderly Care'), ('child_care', 'Child Care'), ('medical_services', 'Medical Services'), ('health_and_safety', 'Health & Safety'), ('vaccines', 'Vaccines'), ('monitor_heart', 'Cardiology'), ('visibility', 'Eye Care'), ('dentistry', 'Dentistry'), ('spa', 'Wellness/Spa'), ('fitness_center', 'Fitness'), ('bloodtype', 'Blood Bank'), ('emergency', 'Emergency'), ('science', 'Research'), ('category', 'General')], default='category', max_length=50)),
                ('color', models.CharField(choices=[('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('orange', 'Orange'), ('cyan', 'Cyan'), ('red', 'Red'), ('pink', 'Pink')], default='blue', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower number = shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='tenant',
            name='category',
            field=models.CharField(choices=[('CLINIC', 'Clinic'), ('PHARMACY', 'Pharmacy'), ('HOSPITAL', 'Hospital'), ('LAB', 'Lab')], default='CLINIC', max_length=30),
        ),
        migrations.AddField(
            model_name='tenant',
            name='category_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='tenants.category'),
        ),
    ]
