# Generated by Django 5.2.11 on 2026-03-06 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_add_category_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='advanced_reports',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='ai_enabled',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='api_access',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='custom_branding',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='export_enabled',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='features',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='lab_addon',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_appointments_per_month',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_doctors',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_patients',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_staff',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='pharmacy_addon',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='sms_enabled',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='whatsapp_enabled',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='tenants.category'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.category')),
            ],
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.feature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='tenants.subscriptionplan')),
            ],
            options={
                'unique_together': {('plan', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='PlanResourceLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_value', models.IntegerField(default=-1)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_limits', to='tenants.subscriptionplan')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.resource')),
            ],
            options={
                'unique_together': {('plan', 'resource')},
            },
        ),
    ]
