# Generated by Django 5.2.11 on 2026-03-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_remove_subscriptionplan_advanced_reports_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['order', 'price']},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which plan appears (lowest first)'),
        ),
    ]
