# Generated by Django 5.2.11 on 2026-02-20 11:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('specialization', models.CharField(choices=[('General', 'General Practice'), ('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('ENT', 'ENT'), ('Neurology', 'Neurology'), ('Ophthalmology', 'Ophthalmology'), ('Gynecology', 'Gynecology'), ('Psychiatry', 'Psychiatry')], default='General', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('qualification', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
