# Generated by Django 5.2.11 on 2026-03-10 03:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('specialization', models.CharField(choices=[('General', 'General Practice'), ('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('ENT', 'ENT'), ('Neurology', 'Neurology'), ('Ophthalmology', 'Ophthalmology'), ('Gynecology', 'Gynecology'), ('Psychiatry', 'Psychiatry'), ('Dentistry', 'Dentistry'), ('Physiotherapy', 'Physiotherapy')], default='General', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('qualification', models.CharField(blank=True, default='', max_length=255)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('follow_up_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_pct', models.DecimalField(decimal_places=2, default=0, help_text='Commission percentage (0–100)', max_digits=5)),
                ('tele_consult_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Link to a user account for login', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subjective', models.TextField(blank=True, help_text="Patient's chief complaints and history")),
                ('objective', models.TextField(blank=True, help_text='Vitals, physical exam findings, lab results')),
                ('assessment', models.TextField(blank=True, help_text='Diagnosis and medical impression')),
                ('plan', models.TextField(blank=True, help_text='Treatment plan, medications, follow-up')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_notes', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='patients.patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='clinical.doctor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, help_text='General instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clinical.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(help_text='e.g., 500mg, 1 tablet', max_length=100)),
                ('frequency', models.CharField(help_text='e.g., Twice a day (1-0-1)', max_length=100)),
                ('duration', models.CharField(help_text='e.g., 5 days', max_length=100)),
                ('instructions', models.TextField(blank=True, help_text='e.g., After food')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinical.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration', models.IntegerField(default=15, help_text='Minutes per slot')),
                ('max_bookings', models.IntegerField(default=1, help_text='Max patients per slot')),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='clinical.doctor')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('doctor', 'day_of_week', 'start_time')},
            },
        ),
    ]
