# Generated by Django 5.2.11 on 2026-03-11 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctorslot',
            name='schedule_date',
            field=models.DateField(default=datetime.date(2026, 3, 11), help_text='The specific date for this slot'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='doctorslot',
            name='day_of_week',
        ),
        migrations.AlterModelOptions(
            name='doctorslot',
            options={'ordering': ['schedule_date', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='doctorslot',
            unique_together={('doctor', 'schedule_date', 'start_time')},
        ),
    ]
