# Generated by Django 5.2.11 on 2026-02-24 09:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='commission_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission percentage (0–100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='follow_up_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='tele_consult_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link to a user account for login', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('General', 'General Practice'), ('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('ENT', 'ENT'), ('Neurology', 'Neurology'), ('Ophthalmology', 'Ophthalmology'), ('Gynecology', 'Gynecology'), ('Psychiatry', 'Psychiatry'), ('Dentistry', 'Dentistry'), ('Physiotherapy', 'Physiotherapy')], default='General', max_length=50),
        ),
        migrations.CreateModel(
            name='DoctorSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration', models.IntegerField(default=15, help_text='Minutes per slot')),
                ('max_bookings', models.IntegerField(default=1, help_text='Max patients per slot')),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='clinical.doctor')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('doctor', 'day_of_week', 'start_time')},
            },
        ),
    ]
