# Generated by Django 5.2.11 on 2026-03-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_alter_doctorslot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending POS'), ('DISPENSED', 'Dispensed')], default='PENDING', help_text='Prescription status in pharmacy workflow', max_length=20),
        ),
    ]
