# Generated by Django 5.2.11 on 2026-03-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='appointment_id',
            field=models.UUIDField(blank=True, help_text='Linked appointment (from tenant schema)', null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='is_billable',
            field=models.BooleanField(default=True, help_text='Charge this item to the patient'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='patient_id',
            field=models.UUIDField(blank=True, help_text='Linked patient (from tenant schema)', null=True),
        ),
    ]
