# Generated by Django 5.2.11 on 2026-03-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocktransaction_appointment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='item_types',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='inventory.itemtype'),
        ),
    ]
