# Generated by Django 5.2.11 on 2026-03-12 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointmentactivity_action'),
        ('labs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lab_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labresult',
            name='pdf_report',
            field=models.FileField(blank=True, null=True, upload_to='lab_reports/'),
        ),
        migrations.AddField(
            model_name='labsample',
            name='collection_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='labtest',
            name='preparation_instructions',
            field=models.TextField(blank=True, help_text='e.g., Fasting for 12 hours'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='sample_type',
            field=models.CharField(blank=True, help_text='e.g., Blood, Urine', max_length=100),
        ),
        migrations.AddField(
            model_name='labtest',
            name='turnaround_time',
            field=models.CharField(blank=True, help_text='e.g., 24 hours', max_length=100),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTED', 'Sample Collected'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REPORT_UPLOADED', 'Report Uploaded'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
