# Generated by Django 5.2.11 on 2026-03-12 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_laborder_appointment_laborder_technician_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTED', 'Sample Collected'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified'), ('REPORT_UPLOADED', 'Report Uploaded'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='LabTestPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tests', models.ManyToManyField(related_name='packages', to='labs.labtest')),
            ],
        ),
        migrations.CreateModel(
            name='LabTestParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('normal_low', models.CharField(blank=True, max_length=100)),
                ('normal_high', models.CharField(blank=True, max_length=100)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='labs.labtest')),
            ],
        ),
        migrations.AddField(
            model_name='labresult',
            name='parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='labs.labtestparameter'),
        ),
    ]
