# Generated by Django 5.2.11 on 2026-03-12 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_alter_laborder_status_labtestpackage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit / Barcode', max_length=100, null=True, unique=True)),
                ('category', models.CharField(choices=[('REAGENT', 'Reagent'), ('CONSUMABLE', 'Consumable'), ('EQUIPMENT', 'Equipment / Part'), ('OTHER', 'Other')], default='REAGENT', max_length=50)),
                ('unit', models.CharField(help_text='e.g., kits, boxes, ml', max_length=50)),
                ('quantity_in_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=10.0, help_text='Alert when stock falls below this level', max_digits=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabInventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ADD', 'Stock Added (Purchase)'), ('CONSUME', 'Stock Consumed (Usage)'), ('ADJUST', 'Manual Adjustment (Correction/Damage)')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Amount added or consumed', max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='labs.labinventoryitem')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabOrderAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='labs.laborder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
