# Generated by Django 5.2.11 on 2026-03-16 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_migrate_lab_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labinventorytransaction',
            name='item',
        ),
        migrations.RemoveField(
            model_name='labinventorytransaction',
            name='performed_by',
        ),
        migrations.DeleteModel(
            name='LabInventoryItem',
        ),
        migrations.DeleteModel(
            name='LabInventoryTransaction',
        ),
    ]
