# Generated by Django 5.2.11 on 2026-02-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='preferred_language',
            field=models.CharField(blank=True, default='English', max_length=50),
        ),
    ]
