# Generated by Django 5.2.11 on 2026-03-10 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, help_text='Doctor primarily responsible for this patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to='clinical.doctor'),
        ),
    ]
