# Generated by Django 5.2.11 on 2026-03-16 05:25

from django.db import migrations

def migrate_medicines(apps, schema_editor):
    Medicine = apps.get_model('pharmacy', 'Medicine')
    InventoryItem = apps.get_model('inventory', 'InventoryItem')
    InventoryBatch = apps.get_model('inventory', 'InventoryBatch')
    ItemType = apps.get_model('inventory', 'ItemType')
    ItemCategory = apps.get_model('inventory', 'ItemCategory')
    
    try:
        med_type = ItemType.objects.get(code='MEDICINE')
    except Exception:
        # If ItemType doesn't exist yet, we silently skip.
        # This can happen in fresh databases or test cases.
        return
        
    for med in Medicine.objects.all():
        cat = None
        if med.category:
            cat = ItemCategory.objects.filter(item_type=med_type, name__icontains=med.category).first()
            
        inv_item, created = InventoryItem.objects.get_or_create(
            sku=med.sku,
            defaults={
                'name': med.name,
                'item_type': med_type,
                'item_category': cat,
                'barcode': med.barcode,
                'min_stock_level': med.min_stock_level,
                'status': med.status,
                'total_stock': med.stock,
            }
        )
        
        if created and med.stock > 0:
            InventoryBatch.objects.create(
                item=inv_item,
                batch_number=med.batch_number or f"BATCH-{med.sku}",
                quantity=med.stock,
                purchase_price=med.purchase_price,
                selling_price=med.price,
                mrp=med.mrp,
                tax_rate=med.tax_rate,
                expiry_date=med.expiry_date
            )

def reverse_migrate(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_purchaseorder_supplier_medicine_barcode_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_medicines, reverse_migrate),
    ]
