# Generated by Django 5.2.11 on 2026-03-16 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocktransaction_appointment_id_and_more'),
        ('pharmacy', '0003_migrate_pharmacy_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='purchasereturnitem',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='medicine',
        ),
        migrations.AlterUniqueTogether(
            name='purchaseinvoice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='purchasereturnitem',
            name='purchase_return',
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_prescription_items', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_sale_items', to='inventory.inventoryitem'),
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='PurchaseInvoice',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItem',
        ),
        migrations.DeleteModel(
            name='PurchaseReturn',
        ),
        migrations.DeleteModel(
            name='PurchaseReturnItem',
        ),
    ]
