# Generated by Django 5.2.11 on 2026-03-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_remove_prescriptionitem_medicine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionitem',
            name='quantity_prescribed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
