# Generated by Django 5.2.12 on 2026-03-18 05:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(blank=True, help_text='Fallback if patient record not linked', max_length=255)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('appointment_type', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('WALK_IN', 'Walk-in'), ('TELE_CONSULT', 'Tele-consult')], default='SCHEDULED', max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20)),
                ('token_number', models.IntegerField(blank=True, null=True)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('no_show', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('BOOKED', 'Booked'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show'), ('RESCHEDULED', 'Rescheduled'), ('STATUS_CHANGED', 'Status Changed')], max_length=20)),
                ('old_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Appointment Activities',
                'ordering': ['performed_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_slot_duration', models.IntegerField(default=15, help_text='Minutes')),
                ('allow_walk_ins', models.BooleanField(default=True)),
                ('auto_confirm', models.BooleanField(default=False)),
                ('cancellation_window_hours', models.IntegerField(default=2)),
                ('no_show_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reminder_hours_before', models.JSONField(blank=True, default=list, help_text='JSON list, e.g. [24, 2]')),
                ('auto_followup_days', models.IntegerField(default=7)),
            ],
        ),
    ]
