# Generated by Django 5.2.11 on 2026-02-24 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0002_patient_marital_status_patient_preferred_language'),
        ('tenants', '0005_subscriptionplan_advanced_reports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('WALK_IN', 'Walk-in'), ('TELE_CONSULT', 'Tele-consult')], default='SCHEDULED', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='no_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='token_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(blank=True, help_text='Fallback if patient record not linked', max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20),
        ),
        migrations.CreateModel(
            name='AppointmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_slot_duration', models.IntegerField(default=15, help_text='Minutes')),
                ('allow_walk_ins', models.BooleanField(default=True)),
                ('auto_confirm', models.BooleanField(default=False)),
                ('cancellation_window_hours', models.IntegerField(default=2)),
                ('no_show_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reminder_hours_before', models.JSONField(blank=True, default=list, help_text='JSON list, e.g. [24, 2]')),
                ('auto_followup_days', models.IntegerField(default=7)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_config', to='tenants.tenant')),
            ],
        ),
    ]
