# Generated by Django 5.2.11 on 2026-03-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointmentactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentactivity',
            name='action',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show'), ('RESCHEDULED', 'Rescheduled'), ('STATUS_CHANGED', 'Status Changed')], max_length=20),
        ),
    ]
