# Generated by Django 5.2.11 on 2026-02-23 05:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('floor', models.IntegerField(default=1)),
                ('head_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_head', to='clinical.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=20, unique=True)),
                ('bed_type', models.CharField(choices=[('GENERAL', 'General Ward'), ('SEMI_PRIVATE', 'Semi-Private'), ('PRIVATE', 'Private Room'), ('ICU', 'ICU'), ('ER', 'Emergency Room')], default='GENERAL', max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Maintenance'), ('RESERVED', 'Reserved')], default='AVAILABLE', max_length=20)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hospitals.department')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ADMITTED', 'Admitted'), ('DISCHARGED', 'Discharged'), ('TRANSFERRED', 'Transferred')], default='ADMITTED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('attending_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.patient')),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.bed')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.department')),
            ],
        ),
    ]
