# Generated by Django 5.2.11 on 2026-02-23 05:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        ('hospitals', '0002_ercase_patientvital_staffshift'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('accreditation_info', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospital_logos/')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_multi_branch', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='admission',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='department',
            name='code',
        ),
        migrations.RemoveField(
            model_name='department',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='department',
            name='head_doctor',
        ),
        migrations.AddField(
            model_name='admission',
            name='discharge_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='expected_discharge',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='clinical.doctor'),
        ),
        migrations.AddField(
            model_name='department',
            name='revenue_tracking',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='bed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.bed'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.department'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DISCHARGED', 'Discharged'), ('CRITICAL', 'Critical'), ('TRANSFER_PENDING', 'Transfer Pending')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='bed',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hospitals.department'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('CLEANING', 'Cleaning'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='hospitals.hospital'),
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=100)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Pre-Auth'), ('APPROVED', 'Pre-Auth Approved'), ('REJECTED', 'Pre-Auth Rejected'), ('CLAIMED', 'Claim Filed'), ('SETTLED', 'Settled')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='hospitals.admission')),
                ('corporate_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.corporateaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('ward_type', models.CharField(default='GENERAL', max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='hospitals.department')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hospitals.ward'),
        ),
    ]
