# Generated by Django 5.2.11 on 2026-02-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_corporateaccount_hospital_remove_admission_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='has_clinic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='has_lab',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='has_pharmacy',
            field=models.BooleanField(default=True),
        ),
    ]
