# Generated by Django 5.2.11 on 2026-02-23 09:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        ('hospitals', '0004_hospital_has_clinic_hospital_has_lab_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffshift',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='has_clinic',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='has_lab',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='has_pharmacy',
        ),
        migrations.AlterField(
            model_name='staffshift',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='clinical.doctor'),
        ),
        migrations.CreateModel(
            name='HospitalStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('NURSE', 'Nurse'), ('TECHNICIAN', 'Lab Technician'), ('PHARMACIST', 'Pharmacist'), ('ADMIN', 'Administrator'), ('SUPPORT', 'Support Staff')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='hospitals.department')),
            ],
        ),
        migrations.AddField(
            model_name='staffshift',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='hospitals.hospitalstaff'),
        ),
    ]
