# Generated by Django 5.2.12 on 2026-03-18 11:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('appointment', 'Appointment'), ('billing', 'Billing'), ('lab', 'Lab Result'), ('system', 'System'), ('campaign', 'Campaign'), ('feedback', 'Feedback'), ('prescription', 'Prescription'), ('payment', 'Payment'), ('alert', 'Alert')], default='system', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('action_url', models.CharField(blank=True, default='', help_text='Relative URL to navigate to when notification is clicked', max_length=500)),
                ('action_text', models.CharField(blank=True, default='View', max_length=100)),
                ('image_url', models.URLField(blank=True, help_text='Optional image for notification', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_address', models.EmailField(blank=True, help_text='Override email', max_length=254, null=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('phone_number', models.CharField(blank=True, help_text='Override phone', max_length=20, null=True)),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('type_preferences', models.JSONField(blank=True, default=dict)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='e.g. 22:00', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='e.g. 07:00', null=True)),
                ('quiet_hours_timezone', models.CharField(default='UTC', max_length=50)),
                ('digest_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('never', 'Never')], default='daily', max_length=10)),
                ('last_digest_sent', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('unsubscribe_all', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_type', models.CharField(choices=[('twilio_sms', 'Twilio SMS'), ('twilio_whatsapp', 'Twilio WhatsApp'), ('sendgrid', 'SendGrid'), ('gupshup', 'Gupshup'), ('firebase', 'Firebase Cloud Messaging'), ('onesignal', 'OneSignal'), ('smtp', 'Custom SMTP'), ('ses', 'AWS SES'), ('sns', 'AWS SNS')], max_length=50)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('push', 'Push')], max_length=20)),
                ('name', models.CharField(help_text='Display name', max_length=100)),
                ('config', models.JSONField(default=dict, help_text='Configuration (keys, endpoints) - store sensitive data in env vars')),
                ('priority', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Use as default for tenant')),
                ('rate_limit_per_minute', models.IntegerField(default=60)),
                ('rate_limit_per_hour', models.IntegerField(default=1000)),
                ('rate_limit_per_day', models.IntegerField(default=10000)),
                ('messages_sent_today', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_providers', to='tenants.tenant')),
            ],
            options={
                'db_table': 'notification_providers',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('recipient_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('recipient_push_token', models.CharField(blank=True, max_length=500, null=True)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('clicked', 'Clicked'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('held', 'Held - Quiet Hours')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, help_text='e.g., twilio, sendgrid', max_length=50)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('in_app_notification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_item', to='notifications.notification')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_queue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('clicked', 'Clicked'), ('failed', 'Failed'), ('retry', 'Retry'), ('fallback', 'Fallback'), ('cancelled', 'Cancelled'), ('held', 'Held'), ('digest_sent', 'Digest Sent')], max_length=20)),
                ('channel', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('consent_at_time', models.BooleanField(default=True, help_text='User had consented at this time')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications.notification')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
                ('queue_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications.notificationqueue')),
            ],
            options={
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='notification_attachments/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.IntegerField(help_text='Size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='notifications.notificationqueue')),
            ],
            options={
                'db_table': 'notification_attachments',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push')], max_length=20)),
                ('notification_type', models.CharField(choices=[('appointment', 'Appointment'), ('billing', 'Billing'), ('lab', 'Lab Result'), ('system', 'System'), ('campaign', 'Campaign'), ('feedback', 'Feedback'), ('prescription', 'Prescription'), ('payment', 'Payment'), ('alert', 'Alert')], max_length=20)),
                ('subject', models.CharField(blank=True, help_text='For email', max_length=255)),
                ('body', models.TextField(help_text='With placeholders like {{patient_name}}')),
                ('preview', models.TextField(blank=True, help_text='Preview with sample data')),
                ('required_variables', models.JSONField(blank=True, default=list)),
                ('optional_variables', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(default='en', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('click_tracking', models.BooleanField(default=True)),
                ('open_tracking', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='tenants.tenant')),
            ],
            options={
                'db_table': 'notification_templates',
            },
        ),
        migrations.AddField(
            model_name='notificationqueue',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate'),
        ),
        migrations.CreateModel(
            name='NotificationCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('user_segment', models.JSONField(default=dict, help_text='Filter criteria for users')),
                ('include_all_users', models.BooleanField(default=False)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('read_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notifications.notificationtemplate')),
            ],
            options={
                'db_table': 'notification_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web (PWA)'), ('huawei', 'Huawei')], max_length=20)),
                ('push_token', models.CharField(db_index=True, max_length=500)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('device_model', models.CharField(blank=True, max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=50)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_devices',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='idx_notif_user'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='idx_notif_unread'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', '-created_at'], name='notificatio_tenant__b31a53_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', '-created_at'], name='notificatio_type_d2e2f1_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['user', 'unsubscribe_token'], name='notificatio_user_id_d00082_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationprovider',
            index=models.Index(fields=['tenant', 'channel', 'is_active'], name='notificatio_tenant__7b2fe4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationprovider',
            unique_together={('tenant', 'provider_type')},
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['tenant', '-created_at'], name='notificatio_tenant__cb58d1_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification'], name='notificatio_notific_aabcef_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['queue_item'], name='notificatio_queue_i_29dad7_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['event_type'], name='notificatio_event_t_2c7753_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_190e63_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['tenant', 'name', 'is_active'], name='notificatio_tenant__8c1f51_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_9dff33_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('tenant', 'name', 'channel', 'language')},
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['tenant', 'status', 'scheduled_for'], name='notificatio_tenant__7c7efc_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_0b53f8_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['provider_message_id'], name='notificatio_provide_2fb6c5_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['status', 'scheduled_for'], name='notificatio_status_27f60e_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user', 'is_active'], name='user_device_user_id_14e9e9_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['push_token'], name='user_device_push_to_602614_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userdevice',
            unique_together={('user', 'push_token')},
        ),
    ]
